In [1]:
import tensorflow as tf
import numpy as np
tf.enable_eager_execution()

In [12]:
init = tf.constant_initializer(1.0)

class periodic_conv2dmodel(tf.keras.Model):
    def __init__(self):
        super(periodic_conv2dmodel, self).__init__()

        # decide how to pad vertically
        self.vert = tf.constant([[0., 0., 1.], [1., 0., 0.], [0., 1., 0.], [0., 0., 1.], [1., 0., 0.]])
        # decide how to pad horizontally
        self.horiz = tf.transpose(self.vert)

        self.Con2DLayer = tf.keras.layers.Conv2D(1, (1, 1), activation='linear', padding='same',kernel_initializer=init) 
        
    def call(self, X):
        # get the 2D input matrix and pad it
        periodically_padded = tf.matmul(tf.matmul(self.vert, X), self.horiz)
        
        # reshape it to a 4D array
        periodically_padded = tf.reshape(periodically_padded , (1,5,5,1) )
        
        # perform a 2D convolution
        output = self.Con2DLayer (periodically_padded)

        return output

In [13]:
model = periodic_conv2dmodel()

In [14]:
feature_map = tf.constant([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.]]) 
print feature_map

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]], shape=(3, 3), dtype=float32)


In [15]:
print model(feature_map).numpy().reshape(5,5)

[[9. 7. 8. 9. 7.]
 [3. 1. 2. 3. 1.]
 [6. 4. 5. 6. 4.]
 [9. 7. 8. 9. 7.]
 [3. 1. 2. 3. 1.]]
